### ISSUE TITLE
Funding Bundlr

### ISSUE THREAD

**Issue by myyellowshoe** [metaplex-foundation/js-next#104]
How would i fund Bundlr through the storage driver? Any examples?

I could pull in the external bundlr package and to it that way but just trying to avoid having 2 of the same packages deps to manage. 

Thanks so much for the great work so far!

**Comment by lorisleiva** [comment]
Hi there 👋 

If you know you're using the Bundlr Storage driver you can cast it in TypeScript like so:

```ts
const bundlrStorage = metaplex.storage() as BundlrStorageDriver;
```

Which mean you now have access to useful public methods such as:

```ts
bundlrStorage.fund([metaplexFile1, metaplexFile2]); // Fund using file size.
bundlrStorage.fund(1000); // Fund using byte size.
bundlrStorage.getBundlr().fund(1000); // Fund using lamports directly.
```

I hope this helps.

**Comment by lorisleiva** [comment]
Hey 👋 

Yeah sorry this was recently change to `metaplex.storage().driver().bundlr()` due to some core architectural refactoring. 🙂
