### ISSUE TITLE
walletAdapterIdenity is showing type error when used with useWallet. 

### ISSUE THREAD

**Issue by Shusanta** [metaplex-foundation/js-next#113]
<img width="310" alt="Screen Shot 2022-05-23 at 1 17 47 PM" src="https://user-images.githubusercontent.com/26209974/169899574-eaa2610f-dc64-47b9-8e51-d1faf7f4f46b.png">
walletAdapterIdenity is showing a type error when used with useWallet.
useWallet is being imported from  '@solana/wallet-adapter-react'

**Comment by Steenos** [comment]
I'm still getting this type error as well

**Comment by lorisleiva** [comment]
@Shusanta do you remember how you fixed this in your app? 🙏

**Comment by Shusanta** [comment]
@lorisleiva a simple version bump fixed this for me. What version are you on @Steenos ?
