### ISSUE TITLE
js-next not compatible with latest @solana/web3.js version

### ISSUE THREAD

**Issue by kunaljaydesai** [metaplex-foundation/js-next#124]
`js-next` library is not compatible with the current version of @solana/web3.js. [Here is a minimal reproducible example](https://github.com/kunaljaydesai/metaplex-dependency)

I get an error message like:
<img width="1290" alt="Screen Shot 2022-06-02 at 9 25 49 AM" src="https://user-images.githubusercontent.com/7613905/171678321-47f390c1-1e2b-4190-a963-a5d38bda1b16.png">

I believe the errors occur because @metaplex-foundation/js-next says it supports @solana/web3.js ^1.37.0, but that's not true anymore. @solana/web3.js deprecated the TransactionCtorFields type between [1.37.0](https://github.com/solana-labs/solana-web3.js/blob/d93efdfe8dd51a91e254a800be63c9157a9fe7cc/src/transaction.ts#L110) and [now](https://github.com/solana-labs/solana-web3.js/blob/master/src/transaction.ts#L134).

I think the solution is to pin the `@solana/web3.js` dependency to `1.37.0` or stop using `TransactionCtorFields` in `js-next`. To solve my problem temporarily, I've pinned the @solana/web3.js dependency in my `package.json` like so:

```
 "resolutions": {
    "@solana/web3.js": "1.37.0"
  }
```

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for raising this. We've already fixed this but we haven't published a new version yet.

We'll do that asap.

**Comment by lorisleiva** [comment]
This was fixed in version `0.10.0` 🚀

**Comment by kunaljaydesai** [comment]
great, thanks!
