### ISSUE TITLE
Fix issue with uploadMetadata and bundlrStorage driver

### ISSUE THREAD

**Issue by DataKnox** [metaplex-foundation/js-next#41]
**Environment:**
Node v17.2
Ubuntu 20.04 LTS

**Issue:**
When performing the uploadMetadata operation, the Buffer appears to be passed the KeypairIdentityDriver at some point.

**Sample code:**
`
    
    const { Metaplex, MetaplexFile, keypairIdentity, bundlrStorage, mockStorage } = require("@metaplex-foundation/js-next");
    const { Connection, clusterApiUrl, Keypair } = require("@solana/web3.js");
    const fs = require('fs')
    const path = require('path')
    const connection = new Connection(clusterApiUrl("devnet"));
    
    let keypairFile = fs.readFileSync('/home/knox/jsnext/newkey.json')
    const keypair = Keypair.fromSecretKey(Buffer.from(JSON.parse(keypairFile.toString())));
    
    const metaplex = Metaplex.make(connection)
        .use(keypairIdentity(keypair))
        .use(bundlrStorage({
            address: 'https://devnet.bundlr.network',
            providerUrl: 'https://api.devnet.solana.com',
            timeout: 60000,
        }))
    
    
    const artPath = '/home/knox/jsnext/art/'
    async function batchCreator() {
        //const mx = await metaplex();
        const { uri, metadata } = await metaplex.nfts().uploadMetadata({
            name: "My NFT #",
            image: new MetaplexFile(Buffer.from('/home/knox/jsnext/art/1.png'), '1.png'),
            properties: {
                files: [
                    {
                        type: "image/png",
                        uri: new MetaplexFile(Buffer.from('/home/knox/jsnext/art/1.png'), '1.png'),
                    },
                ]
            }
        });
    
        console.log(metadata.image) // https://arweave.net/123
        console.log(metadata.properties.files[0].uri) // https://arweave.net/456
        console.log(uri) // https://arweave.net/789
    }
    
    
    
    batchCreator();
`

Result: 
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
(node:1327) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of KeypairIdentityDriver
    at new NodeError (node:internal/errors:371:5)
    at Function.from (node:buffer:322:9)
    at SolanaConfig.getKeyPair (/home/knox/jsnext/js-next-examples/node_modules/@bundlr-network/client/build/node/currencies/solana.js:54:48)
    at SolanaConfig.getPublicKey (/home/knox/jsnext/js-next-examples/node_modules/@bundlr-network/client/build/node/currencies/solana.js:159:26)
    at new BaseNodeCurrency (/home/knox/jsnext/js-next-examples/node_modules/@bundlr-network/client/build/node/currency.js:16:64)
    at new SolanaConfig (/home/knox/jsnext/js-next-examples/node_modules/@bundlr-network/client/build/node/currencies/solana.js:39:9)
    at getCurrency (/home/knox/jsnext/js-next-examples/node_modules/@bundlr-network/client/build/node/currencies/index.js:28:20)
    at new NodeBundlr (/home/knox/jsnext/js-next-examples/node_modules/@bundlr-network/client/build/node/bundlr.js:24:56)
    at BundlrStorageDriver.<anonymous> (/home/knox/jsnext/js-next-examples/node_modules/@metaplex-foundation/js-next/dist/cjs/drivers/storage/BundlrStorageDriver.js:143:19)
    at Generator.next (<anonymous>) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**NOTES**
The operation works fine with mockStorage(). I will test with aws and see if this has any impact

**Comment by lorisleiva** [comment]
Ha yeah sorry I've tested Bundlr on the Browser but I've not had the chance to test it yet on the CLI so that's probably why. I'll take a look when I have a moment. 🙂

**Comment by DataKnox** [comment]
> Ha yeah sorry I've tested Bundlr on the Browser but I've not had the chance to test it yet on the CLI so that's probably why. I'll take a look when I have a moment. 🙂

Note I was able to fix this... sort of. Since Bundlr is receiving a KeypairIdentityDriver, it does have access to the key
pair property. Looking at how the Bundlr client is built, it builds from the secret key property.

In:
../node_modules/@metaplex-foundation/js-next/dist/cjs/drivers/storage/BundlrStorageDriver.js

Change line 143 to zip down to the secretKey
 const bundlr = this.metaplex.identity() instanceof WalletAdapterIdentityDriver_1.WalletAdapterIdentityDriver
                ? new client_1.WebBundlr(address, currency, this.metaplex.identity(), options)
                : new client_1.default(address, currency, this.metaplex.identity().keypair.secretKey, options);


Note that the main branch has different code than what is present here so I cannot submit a PR. The main branch does not reference a KeypairIdentityDriver, but rather just an IdentityDriver which does not have access to the keypair attribute or the secretKey.

**Comment by DataKnox** [comment]
Submitted a PR after all!

**Comment by DataKnox** [comment]
Issue closed with #42
