### ISSUE TITLE
UpdateNft sets isMutable to true by default

### ISSUE THREAD

**Issue by anoushk1234** [metaplex-foundation/js-next#44]
When using the updateNft function youll get an error if you dont specify isMutable:false in the UpdateNftOperation params. You can't set isMutable to true once the NFT is created whether you set isMutable to true or false while creating it

Solution would be to set the value to false by default in update params

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for raising this. I can see how this would be confusing but I wouldn't want to create mutable NFTs by default because the SDK should be as secure as possible by default. Mutable NFTs should be explicit. However, the documentation could be improved to make that clearer.

**Comment by anoushk1234** [comment]
> Hi there 👋 
> 
> 
> 
> Thanks for raising this. I can see how this would be confusing but I wouldn't want to create mutable NFTs by default because the SDK should be as secure as possible by default. Mutable NFTs should be explicit. However, the documentation could be improved to make that clearer.

Yea would be better to mention this in the docs and in the function itself as vs code can point it out
