### ISSUE TITLE
Can't import @metaplex-foundation/js-next: Error: Directory import

### ISSUE THREAD

**Issue by zkhalapyan** [metaplex-foundation/js-next#84]
> Error: Directory import '~/flex/node_modules/@metaplex-foundation/js-next/dist/esm/drivers' is not supported resolving ES modules imported from ~/flex/node_modules/@metaplex-foundation/js-next/dist/esm/index.js

Trying to import the NPM library into my TypeScript project: `import { Metaplex, keypairIdentity } from "@metaplex-foundation/js-next";`

**Comment by lorisleiva** [comment]
Hi there 👋

Thanks for raising this. Could you please provide the following information?

- Which SDK version are you using?
- Are you using a bundler such as Webpack?
- Can you give me the steps to reproduce this?

**Comment by zkhalapyan** [comment]
Thanks for adding more context @ad0ll! 

@lorisleiva if you need help with creating next js app, here is a good [starter](https://nextjs.org/docs/api-reference/create-next-app).

Essentially, here are the steps:
1.  Run `npx create-next-app@latest --ts`
2. Then run `npm install @metaplex-foundation/js-next` 
3. Open `index.tsx`
4. Then you try to import via code, `import { Metaplex, keypairIdentity } from "@metaplex-foundation/js-next";`
5. If you have VSCode setup, you should be warned of an error; if not try to run `npm run dev` on your terminal and it should present the error above. 

Hope this is helpful. If not, I can create an exact project and attach it here.

**Comment by na** [comment]
I was getting the same error and got this working with Nextjs using require instead of import.    

```
const Metaplex = require("@metaplex-foundation/js-next").Metaplex;
const connection = new Connection(clusterApiUrl("mainnet-beta"));
const metaplex = new Metaplex(connection)
```

**Comment by zkhalapyan** [comment]
@na checkout issue #85... I am little afraid that using require could cause other problems down the line.

**Comment by lorisleiva** [comment]
Hi there 👋 

I've managed to fix Next.js issues and released version `0.8.2`.

Would you be able to try it out and let me know if you encounter any other issues?

In the meantime, I'll be working on adding a "getting started with Next.js" example on [the example repo](https://github.com/metaplex-foundation/js-examples).

**Comment by na** [comment]
After getting the latest this directory import error does not occur any longer.

**Comment by lorisleiva** [comment]
Thank you for confirming this!
